### ISSUE TITLE
"on":["change"] is unusable

### ISSUE THREAD

**Issue by safinaskar** [tamayika/vscode-any-lint#1]
Hi. `"on":["change"]` is unusable. I pass file name to linter using `"args":["${file}"]`. Thus linter gets file name and thus linter will read file from disk. So, linter gets saved copy! Not modified copy from buffer

**Comment by tamayika** [comment]
Thanks for reporting the issue!
I have fixed it by passing current buffer by STDIN at #2 and released 0.1.0.
If your linter does not support stdin mode, it is difficult to use on text changed.
Please refer the example [here](https://github.com/tamayika/vscode-any-lint/blob/main/examples/eslint-on-change.jsonc).

**Comment by safinaskar** [comment]
@tamayika , I tested, it works
