### ISSUE TITLE
Ignore location : currentLine wrapped?

### ISSUE THREAD

**Issue by mgzenitech** [tamayika/vscode-any-lint#18]
![Screenshot from 2024-07-17 17-03-44](https://github.com/user-attachments/assets/4649e46f-3b7f-461e-ac63-5bc53094a3c2)

Trying now to add ignore lines :)

Based on info @ https://dotenv-linter.github.io/#/usage/check?id=skip-checks

dotenv-linter has to wrap the line with comments before and after:
```
# dotenv-linter:off UnorderedKey
FOO=BAR
# dotenv-linter:on UnorderedKey
```

Right now I can only disable it for either whole file or any line below this one:
```json
          {
            "comment": "`# dotenv-linter:off ${$$.ruleId}`",
            "location": "previousLine",
            "title": "`Ignore ${$$.ruleId} rule for entire file`",
            "type": "ignore"
          }
```

Maybe we could have something like:
```json
"location": "currentLine",
"comment": "`# dotenv-linter:off ${$$.ruleId}\n${currentLine}\n# dotenv-linter:on ${$$.ruleId}`"
```
?
If the `currentLine` would be exposed as variable we could just prepend and append those lines directly. What do you think?

Or even better way would be to have new location: `wrapCurrentLine` or something similar
```json
"location": "wrapCurrentLine",
"comment": [
    "`# dotenv-linter:off ${$$.ruleId}`",
    "`# dotenv-linter:on ${$$.ruleId}`"
]
```

**Comment by tamayika** [comment]
I added `rewriteLine` location and released `0.3.3`.
Please check [documentation](https://github.com/tamayika/vscode-any-lint?tab=readme-ov-file#ignore).
