### ISSUE TITLE
diagnostic > run fails with "The "options.cwd" property must be of type string or an instance of Buffer or URL. Received an instance of Promise"

### ISSUE THREAD

**Issue by mgzenitech** [tamayika/vscode-any-lint#19]
```
          {
            "args": [
              "run",
              "dotenv-linter",
              "fix",
              "-q",
              "${file}"
            ],
            "binPath": "`poetry`",
            "cwd": "${workspaceFolder}",
            "lintAfterRun": "true",
            "title": "`Fix all fixable problems`",
            "type": "run"
          }
```

(that's same as running `dotenv-linter fix -q ${file}`)

When clicking on this action I get this:
![Screenshot from 2024-07-18 12-55-46](https://github.com/user-attachments/assets/78493dbc-bdab-4555-8019-0209dd83e5c8)

**Comment by tamayika** [comment]
Thanks for the report.
Please wait for the next release.

**Comment by mgzenitech** [comment]
@tamayika I think something's still off...

```
          {
            "args": [
              "`run`",
              "`dotenv-linter`",
              "`fix`",
              "`-q`"
              // "${file}"
            ],
            "binPath": "`poetry`",
            // "cwd": "${workspaceFolder}",
            "lintAfterRun": "true",
            "title": "`Fix all fixable problems`",
            "type": "run"
          }
```

When I uncomment any line with `${}` any-lint would stop showing anything related to actions. Could there be a bug somewhere in there?

**Comment by tamayika** [comment]
In `run` action, you must use js expression.
So, `${file}` is making syntax error as js expression.
```json
          {
            "args": [
              "`run`",
              "`dotenv-linter`",
              "`fix`",
              "`-q`",
              "$.file"
            ],
            "binPath": "`poetry`",
            "cwd": "$.workspaceFolder",
            "lintAfterRun": "true",
            "title": "`Fix all fixable problems`",
            "type": "run"
          }
```

**Comment by mgzenitech** [comment]
> In `run` action, you must use js expression. So, `${file}` is making syntax error as js expression.
> 
> ```json
>           {
>             "args": [
>               "`run`",
>               "`dotenv-linter`",
>               "`fix`",
>               "`-q`",
>               "$.file"
>             ],
>             "binPath": "`poetry`",
>             "cwd": "$.workspaceFolder",
>             "lintAfterRun": "true",
>             "title": "`Fix all fixable problems`",
>             "type": "run"
>           }
> ```

May I suggest normalizing same options?

Right now we have this:

```json
  "any-lint.linters": [
    {
      "args": [
        "run",
        "dotenv-linter",
        "-q",
        "${file}"
      ],
      "binPath": "poetry",
      "cwd": "${workspaceFolder}",
      ...
    }
]
```
vs
```json
      "diagnostic": {
        "actions": [
          {
            "args": [
              "`run`",
              "`dotenv-linter`",
              "`fix`",
              "`-q`",
              "`--no-backup`",
              "$.file"
            ],
            "binPath": "`poetry`",
            "cwd": "$.workspaceFolder",
            ...
          }
       ]
    }
```

If parsing with js is needed then probably also the non diagnostic action options should also follow same format? :)

**Comment by tamayika** [comment]
No, configuration of linter execution does not need dynamic evaluation because it is before linter execution.
It should be the same as vscode standard configuration.
