### ISSUE TITLE
any-lint should re-trigger on window reload

### ISSUE THREAD

**Issue by mgzenitech** [tamayika/vscode-any-lint#22]
So I've observed that when file tab is left open in VSCode and window is reloaded
![Screenshot from 2024-07-19 08-56-11](https://github.com/user-attachments/assets/38fb6e48-5c68-46d7-8810-951625b8ed83)

any-lint doesn't re-trigger cli thus not showing errors if they existed before. Only way is to re-save the file. This looks like a bug?

**Comment by tamayika** [comment]
This will be fixed in the next release.
However, when you are opening several tabs before reloading, vscode restores files in active tabs only.
Files in inactive tabs are opened when its tab is activated.
