### ISSUE TITLE
Meaningless error message Error: Illegal value for `line`

### ISSUE THREAD

**Issue by ezh** [tamayika/vscode-any-lint#3]
There is a basic golang linter:
```
		"any-lint.linters": [
			{
				"name": "golint",
				"binPath": "golint",
				"condition": "$.fileExtname == '.go'",
				"args": [
					"${fileDirname}/..."
				],
				"diagnostic": {
					"output": "stdout",
					"type": "lines",
					"format": "${file}:${startLine}:${startColumn}: ${message}",
				}
			}
		]
```

I get the next message on `any-lint` console
```
golint /Users/john/app/pkg/endpoint/...
/Users/john/app/pkg/endpoint/new.go:3:1: exported function New should have comment or be unexported

failed to convert to diagnostic
Error: Illegal value for `line`
```

`/Users/john/app/pkg/endpoint/new.go:3:1: exported function New should have comment or be unexported` is the single line message on STDOUT from `golint`. There are no leading or trailing lines.

**Comment by ezh** [comment]
Is there any hint on how to fix it?

**Comment by ezh** [comment]
Actually, it doesn't depend on 'golint'. I see that other line linters are failed as well.

**Comment by tamayika** [comment]
In my environment(Windows, macOS, Linux), it works with provided configuration.
(In Windows I can't specify `...` for args by access error, so I removed it)

If you can debug extension, please see https://github.com/tamayika/vscode-any-lint/blob/main/src/linter.ts#L154-L155 error's stacktrace.

1. Clone this repo
2. `cd vscode-any-lint && npm install`
3. `code .` to launch vscode
4. Set breakpoint to https://github.com/tamayika/vscode-any-lint/blob/main/src/linter.ts#L154-L155
5. Press F5 to launch test vscode instance
6. Move to your directory in test vscode instance
7. Save the document and lint it in test vscode instance
8. Breakpoint is hit and see the stack trace

**Comment by ezh** [comment]
@tamayika Thank you for the instructions. 💯 
I'm sorry for the noise.
I'll try to reproduce and collect all necessary debug information.

**Comment by ezh** [comment]
I thought that It might be worse to add details to the error message in the vscode console for end-users. So someone could understand errors without a debugger.
