### ISSUE TITLE
Run lint on file open

### ISSUE THREAD

**Issue by sasq64** [tamayika/vscode-any-lint#8]
Linter should run when a file is opened, at least in "change" mode.

**Comment by tamayika** [comment]
I published 0.2.1 which lint files on opening documents and clear diagnostics on closing documents.

**Comment by sasq64** [comment]
Thanks, works fine!

**Comment by sasq64** [comment]
... spoke too soon, it often doesn't clear/reload when you switch files.

Seems to always work the first time you open a file after starting VSCode, but when you switch back to it it doesn't update.

**Comment by tamayika** [comment]
I think it's too aggressive to lint when changing opened documents for single file linting.
So, I will add new event for `on` setting.

**Comment by sasq64** [comment]
Ok, but you should make sure you at least clear when switching.
Also would be good to be able to tell if there are no errors in the file, or if the linter just hasn't run...

**Comment by tamayika** [comment]
I don't think it is necessary to clear when switching to other documents.
Please tell me your usecase in detail.

**Comment by sasq64** [comment]
You work one one file that has errors, you switch to another file and the errors from the old file are still listed which is confusing...

**Comment by tamayika** [comment]
I think it is normal to show multiple files errors in vscode.
Why do you need to suppress other file errors even if it has actually lint errors?
